# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mobtown Fermentation | Wild Kombucha
email: mobtownfermentation@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mobtown Fermentation brews Wild Kombucha right here in Baltimore.
  Our goal is to share this delicious and healthy kombucha with our community.
keywords: Wild Kombucha Mobtown Fermentation Baltimore health delicious fermented
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: WILDKombucha
github_username:  mobtownfermentation

# Build settings
markdown: kramdown
